# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lDFFiZ6_AHUt7Z0kuS1onojrEMQlWKPN

# **CALCULADORA**
"""

import math  # Importa a biblioteca math para usar funções matemáticas (ex: raiz quadrada)

# Função responsável por realizar os cálculos
def calcular(num1, operador, num2=None):
    # Soma
    if operador == '+':
        return num1 + num2

    # Subtração
    elif operador == '-':
        return num1 - num2

    # Multiplicação
    elif operador == '*':
        return num1 * num2

    # Divisão (com verificação para evitar divisão por zero)
    elif operador == '/':
        return num1 / num2 if num2 != 0 else "Erro: divisão por zero"

    # Potência (ex: 2^3 = 8)
    elif operador == '^':
        return num1 ** num2

    # Raiz quadrada (usa apenas um número)
    elif operador == 'r':
        return math.sqrt(num1)

    # Retorna o maior número entre dois valores
    elif operador == '>':
        return num1 if num1 > num2 else num2

    # Retorna o menor número entre dois valores
    elif operador == '<':
        return num1 if num1 < num2 else num2

    # Caso o operador não seja reconhecido
    else:
        return "Operador inválido"


# ---------------- PROGRAMA PRINCIPAL ----------------

print("=== Calculadora Interativa ===")
nome = input('Qual é o seu nome? ')
print(f'Olá {nome}, vamos começar os cálculos')

# Solicita o primeiro número ao usuário
resultado = float(input("Digite o primeiro número: "))

# Loop principal que mantém a calculadora rodando
while True:
    # Usuário escolhe a operação matemática
    operador = input("Escolha a operação:\n+ (soma)\n- (subtração)\n* (multiplicação)\n/ (divisão)\n^ (potência)\nr (raiz quadrada)\n> (maior número)\n< (menor número)\nDigite o operador: ")

    # Se for raiz quadrada, não precisa de segundo número
    if operador == 'r':
        resultado = calcular(resultado, operador)

    else:
        # Solicita o segundo número
        num2 = float(input("Digite o próximo número: "))

        # Chama a função calcular passando os valores
        resultado = calcular(resultado, operador, num2)

    # Mostra o resultado parcial (após cada operação)
    print(f"Resultado atual: {resultado}")

    # Pergunta se o usuário quer continuar calculando
    continuar = input("Deseja continuar? (s/n): ").lower()

    # Se a resposta for diferente de 's', encerra o programa
    if continuar != 's':
        print(f"\nResultado final: {resultado}")
        break  # Encerra o loop